[workspace]
members = [
  "economy-data-api",
  "economy-data-ingest",
  "poeledger-economy-data",
  "poe-api-client",
  "poe-types",
  "stash-processor",
  "river-crawler",
  "price-history-api",
]
resolver = "2"
