version: "3"

services:
  economy-data-api:
    build: economy-data-api/
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - SURREAL_HOST=ws://surrealdb:8000
      - SURREAL_USER=admin
      - SURREAL_PASS=admin
    x-develop:
      watch:
        - action: rebuild
          path: economy-data-api/src/
        - action: rebuild
          path: economy-data-api/Cargo.toml
  surrealdb:
    build: economy-data-db/
    entrypoint: 
      - /surreal 
      - start 
      - --user
      - admin
      - --pass
      - admin
      - file:/.data/surrealdb/economy.db
    ports:
      - "8000:8000"
    volumes:
      - ./.data/surrealdb/:/.data/surrealdb/
