version: "3"

services:
  economy-data-api:
    build: economy-data-api/
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://admin:password@mongodb:27017/
    x-develop:
      watch:
        - action: rebuild
          path: economy-data-api/src/
        - action: rebuild
          path: economy-data-api/Cargo.toml
  mongodb:
    build: economy-data-db/
    ports:
      - "27017:27017"
    volumes:
      - .data/mongodb/:/var/lib/mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
