services:
  nats:
    image: "nats:latest"
    container_name: nats-server
    hostname: nats-server
    volumes:
      - ${PWD}/infra/local/nats/server.conf:/etc/nats/server.conf
      - ${PWD}/.data/nats:/data
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "--config /etc/nats/server.conf"
  clickhouse:
    image: "clickhouse/clickhouse-server:23.4"
    container_name: clickhouse
    hostname: clickhouse
    volumes:
      - ${PWD}/infra/local/clickhouse/server/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/infra/local/clickhouse/server/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/.data/clickhouse:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    depends_on:
      - clickhouse-keeper
  clickhouse-keeper:
    image: "clickhouse/clickhouse-keeper:23.4-alpine"
    container_name: clickhouse-keeper
    hostname: clickhouse-keeper
    volumes:
      - ${PWD}/infra/local/clickhouse/keeper/config.xml:/etc/clickhouse-keeper/keeper_config.xml
    ports:
      - "9181:9181"
  meilisearch:
    image: "getmeili/meilisearch:v1.7"
    container_name: meilisearch
    hostname: meilisearch
    volumes:
      - ${PWD}/.data/meilisearch:/meili_data
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=local-key
