app = "poeledger-economy-data-api"
primary_region = "bos"

[experimental]
auto_rollback = true

[http_service]
internal_port = 5000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
