config:
  http_port: 8222
  max_payload: 8Mi
  cluster:
    enabled: true
    replicas: 3
  jetstream:
    enabled: true
    max_memory_store: 1Gi
    fileStore:
      pvc:
        size: 15Gi
  merge:
    max_payload: << 8MB >>
    jetstream:
      max_memory_store: << 1GB >>

container:
  env:
    # different from k8s units, suffix must be B, KiB, MiB, GiB, or TiB
    # should be ~90% of memory limit
    GOMEMLIMIT: 1844MiB
  merge:
    resources:
      requests:
        cpu: "1"
        memory: 2Gi
      limits:
        cpu: "1"
        memory: 2Gi

podTemplate:
  topologySpreadConstraints:
    kubernetes.io/hostname:
      maxSkew: 1
      whenUnsatisfiable: DoNotSchedule
